# Generated by Django 2.0.3 on 2018-05-18 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_addresss_postcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_img', models.ImageField(upload_to='static/images/goods')),
                ('goods_name', models.CharField(max_length=20, verbose_name='')),
                ('goods_price', models.FloatField(verbose_name='')),
                ('goods_count', models.IntegerField(verbose_name='')),
                ('goods_subtotal', models.FloatField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('order_address', models.CharField(max_length=200, verbose_name='收货地址')),
                ('order_total', models.FloatField(verbose_name='总计金额')),
                ('status', models.BooleanField(default=False, verbose_name='是否付款')),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
            ],
        ),
        migrations.AddField(
            model_name='myorderitem',
            name='myorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myorder.OrderInfo'),
        ),
    ]
