# Generated by Django 2.0.3 on 2018-05-15 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategeoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate', models.CharField(default='数码产品', max_length=20, null=True, verbose_name='商品分类')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='商品名称')),
                ('content', models.TextField(default='掌柜非常懒，什么也没有留', null=True, verbose_name='商品介绍')),
                ('sku', models.IntegerField(default=0, null=True, verbose_name='库存')),
                ('sale', models.IntegerField(default=0, null=True, verbose_name='销量')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='价格')),
                ('unit', models.CharField(default='', max_length=20, null=True, verbose_name='单位')),
                ('pic', models.ImageField(default='goods/default.jpg', null=True, upload_to='goods/', verbose_name='商品图片')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='上架时间')),
                ('pv', models.IntegerField(default=0, null=True, verbose_name='访问量')),
                ('recommond', models.BooleanField(default=False, verbose_name='商品推荐')),
                ('cate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.CategeoryInfo', verbose_name='商品分类')),
            ],
        ),
    ]
