# Generated by Django 2.0.3 on 2018-05-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categeoryinfo',
            name='cate',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='商品分类'),
        ),
    ]
