# Generated by Django 2.0.3 on 2018-05-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=20, verbose_name='密码')),
                ('email', models.CharField(default='xxx@163.com', max_length=30, verbose_name='邮箱')),
                ('phone', models.CharField(default='15555555555', max_length=11, verbose_name='手机号')),
            ],
        ),
    ]
